### ISSUE TITLE
Dagon in blender

### ISSUE THREAD

**Issue by Reaper10** [Senscape/Dagon#118]
It would be cool to see Dagon engine as a  part of blender.
http://www.blender.org/

**Comment by agustincordes** [comment]
I'd love to work closer with Blender. Some folks actually produced some add-ons for Blender supporting Dagon. More info here:

http://forum.senscape.net/index.php?topic=1364.0
http://forum.senscape.net/index.php?topic=1205.0

We'll keep working on the engine eventually, we happen to be very busy with Asylum right now!
