### ISSUE TITLE
lookAt command needs adjustments

### ISSUE THREAD

**Issue by civanT** [Senscape/Dagon#121]
"lookAt" command uses wrong direction to reach its target (long way around instead of the shortest way) in certain situations. 

Also sometimes it doesn't go to the exact point it should go to and misses the target due to the camera speed.

**Comment by bd339** [comment]
Do you have an example / test-case of when it will always take the long way around? I think I know how to fix at least that part of this issue, so a test case to verify that the solution is correct would be awesome :)

**Comment by civanT** [comment]
You can go to Hotel.lua line 433 and delete it and put all of these in:

```
lookAt(0,0)
sleep(1)
lookAt(270,0)
```

Now at the start of the demo you can click on the big sign with rules written on it and the camera will go back, wait a sec and it will go long way around to the second point.

There might be other ways to create the problem, but I can't consistently do it. Hope this helps you!

**Comment by bd339** [comment]
Thanks for the test case btw - it's not that I've given up on this, it's just that I forgot about writing you back. This test case works wonderfully in showing that the `lookAt` command doesn't work wonderfully :)
The fix I thought would work unfortunately only made things worse. It would literally spin around forever! It seems the horizontal angle is not allowed to be negative which breaks my fix. So I will probably need to speak to Agustín about this one.
