### ISSUE TITLE
Stopped Audio restarts when switching Nodes

### ISSUE THREAD

**Issue by bd339** [Senscape/Dagon#147]
Civan and I were discussing what we both consider to be a bug: Lets say a Room has some Audio that autoplays (background ambiance). You find yourself in Node A and the audio stops because of `MyAudio:stop()`. Then you switch to Node B and this will make `MyAudio` play again!

This behaviour seems to be intentional, considering this snippet from Control.cpp (L870-L888)

    // This has to be done every time so that room audios keep playing
    if (_currentRoom->hasAudios() && (!_currentRoom->currentNode()->isSlide() && theTarget != NULL)) {
      //log.trace(kModControl, "Managing environmental sounds...");
      std::vector<Audio*>::iterator it;
      std::vector<Audio*> arrayOfAudios = _currentRoom->arrayOfAudios();
      
      it = arrayOfAudios.begin();
      
      while (it != arrayOfAudios.end()) {
        if ((*it)->state() != kAudioPlaying)
          (*it)->fadeIn();
        audioManager.requestAudio((*it));
        if ((*it)->doesAutoplay()) {
          (*it)->play();
        }
        
        ++it;
      }
    }

This means that whenever we switch from something that is not a Slide to something that is not a Slide, autoplaying music will be restarted.

**Comment by bd339** [comment]
Btw @civanT I can confirm that redefining our test Audio as `HotelAmbiance2 = Audio("ambiance_islesbury.ogg", {volume = 60, loop = true, auto = false}) --hotel entrance and back`
does stop the restarting of the sound. Further evidence this code is the reason.
I also see us hitting this code in the debugger every time we switch, so I say there's no doubt that this is what's causing us trouble.

Now how do we fix it without breaking something else @agustincordes ?

**Comment by civanT** [comment]
Yes, I tested it, too. Disabling "auto" stops audio from starting at Node changes. But when Audio is enabled, problem returns.

**Comment by bd339** [comment]
Indeed. A simple fix would be to just remove that code, but whoever wrote it probably meant something else by it, so we might end up breaking something else - possibly someone's game.

**Comment by agustincordes** [comment]
Yes, I understand the problem now and the rationale behind this code is... plain laziness. Sorry! :blush:

It's simple: whenever a node is switched, I never check what audios are contained in the next node. Any current audios are stopped because, ideally, the engine would resolve whether an audio is needed or not. So if a node has a local special FX, you don't have to worry about explicitly stopping that SFX when you leave said node.

I wouldn't have to stop any audios if I made sure first which audios need persistence across the room (ie: room ambiances, a SFX shared by two nodes), but truth is I never did that code. Plus Control.cpp is by far the worst file in the whole engine -- the first code I ever did for it, and it shows :(

As you correctly realized, the "auto" tag defines that behavior. I think we should go ahead and scrap whatever needs to be scrapped. Worst case scenario we break compatibility with the Asylum teaser and/or Serena, but both projects needed maintenance anyway.

**Comment by agustincordes** [comment]
PS: It's been a *long* time since this, so it's possible there was another reason why I did what I did. Always wanted to make things work "magically" in the script, with mixed results.

**Comment by bd339** [comment]
It's okay, I don't blame you, like you said: that code is from long ago :wink: 
You are also very correct that Control.cpp is a right mess. Alas, the numerous times I've wanted to do something about the many FIXMEs and TODOs I too succumbed to laziness and ended up just leaving my own behind. Sorry about that, future me :grin:

On a serious note, I will fiddle with this code to see if we can at least get desired behaviour for Seclusion and then we will take the rest from there.

**Comment by bd339** [comment]
To add to that last bit of my previous comment: Like you said Agustín, a switch of Nodes will stop all Audio so just removing this code won't be quite enough actually. The quick solution would be to also remove the code that stops all Audio. This would mean users would have to manage Node specific Audio by themselves - something I don't consider terrible since they have the enter/leave events for Nodes. Potentially more troublesome however, is that not only is Audio stopped, the data is also released so if we remove that code more Audio data will be kept in memory. Notice that I am only talking about removing the "Audio release code" from the Node case when we switch, so we would at most keep the Audio data for an entire Room at a time.
Would this be troublesome Agustín?

**Comment by agustincordes** [comment]
Hhmmm, I think that enforcing use of enter/leave events for *all* nodes containing audios will be a burden to the developer. I'd rather stick with something patchier but practical. I'll think some more about it...

**Comment by bd339** [comment]
Fair enough. How much effort do you think it will take to do this properly then?

Actually I'm not even sure what is meant by "Audio in a Node". Like, I know rooms can have Audio objects added to them, and I know Spots can have Audio attached to them. I also know a Node can have its footstep Audio set and "free Audio" can be played (`play("audio.ogg")`). Which of these types of Audio do we want start/stopped when we switch Nodes?

**Comment by agustincordes** [comment]
Ah yes, "Audio in Nodes" is short for "Nodes with Spots with Audios attached". And there's plenty of cases that would benefit from automatic start of audio playback. For instance, the buzzing flies in the Asylum teaser. To achieve such simple effects, you just need to create a spot, attach a video, attach an audio, and you're set. You're bound to create *lots* of similar effects -- imagine now having to manually start/stop them whenever you switch nodes. Hence this (admittedly flawed) audio system.

**Comment by bd339** [comment]
Alright, I see. In that case perhaps we can just alter the code a little instead of removing it.

Specifically what I'm thinking is we leave room audio alone, free audio too. Then we loop over the current node's spots disabling all of the audio that has autoplay (perhaps must have loop too?), switch to the new node, loop over all of its spots and enable those that have autoplay (perhaps must have loop too?).

I think that should cover the majority of "Audio in Nodes" leaving only edge cases for manual treatment (enter/leave event) and at the same time the engine is a lot less intrusive and doesn't override ones decision to stop one bg music (tied to Room) and start another.

**Comment by agustincordes** [comment]
Yes, though *ideally* it would be more efficient to poll the target Node first and confirm which current Spots have attached Audios that would have to be replayed. That way, if a Spot in the next target Node contains an Audio with the "autoplay" tag, we won't need to stop/play the file -- we just let it alone :)

**Comment by bd339** [comment]
Right. Just to be sure: We are talking about a spot S1 in node N1 has audio object A1 attached and so does spot S2 in node N2. So if A1 has the autoplay tag we don't touch A1 either when we switch to N2. Correct?

**Comment by agustincordes** [comment]
That's correct! The audio reference must be the same, that is, it's a shared audio object between two spots in two different nodes.

**Comment by bd339** [comment]
It worked!

**Comment by bd339** [comment]
Closing this because Civan and I can confirm that the change in #148 corrects this behaviour for Seclusion.
