### ISSUE TITLE
Retain count for Audio objects increase at inconvenient times

### ISSUE THREAD

**Issue by bd339** [Senscape/Dagon#149]
@civanT discovered a bug in the destruction of Audio objects through his testing in Seclusion.

It can be reproduced by having an audio object (autoplay) that is added to a Room, then stopping that Audio object with `MyAudio:stop()` and starting it again with `MyAudio:play()`. When you switch to another Room with some different autoplay audio, `MyAudio` will be playing mixed in with the new Room's audio.

The reason is that calling `play` on `MyAudio` will do this: https://github.com/Senscape/Dagon/blob/master/src/AudioProxy.h#L89 and `requestAudio` will increase the object's retain count. So when we switch to the new Room, the audio manager will be cleared (https://github.com/Senscape/Dagon/blob/master/src/Control.cpp#L642) and that will decrease the retain count by one. Problem is, before the increase it was already 1 (presumably because it is set to autoplay) so when we decrease, the retain count will not reach zero and therefore the Audio object will not be destroyed.

**Comment by bd339** [comment]
@agustincordes I don't understand the retain system and thus when and why the retain count should be altered so I really hope this is something you can provide some insight on.

**Comment by agustincordes** [comment]
Phew, it's been a **long** time since I worked on that retain system which is partially inspired by Object-C. In short, since a given Audio object can be shared by different spots, the idea was to keep an internal track of how many times that audio has been requested. When the unload() method is invoked, the engine considers if there are any other pending references; if true, it keeps the audio in memory, and if not, it proceeds to unload it.

I can see how this system may pose a conflict with the changes to the new Audio-SFX-while-switching-Nodes mechanism. Sorry, it's a while since I worked on any of this and many features remain incomplete :(

**Comment by bd339** [comment]
As a matter of fact, I don't think this was directly influenced by the changes in #148 . You see, I explicitly used the developer console to switch between rooms so I can confirm that the node switching case was never hit and as far as I can tell, what happens when you switch rooms shouldn't have been affected by #148.

My opinion is that a simpler solution would be to just unload all room specific audio, along with all audio attached to spots only when we switch rooms. That way we should never encounter a situation where audio is unloaded early. On the contrary we might encounter it being unloaded "too late" - as in we keep it in memory longer than we need. I really don't see this being a problem - unless people create massively complex rooms - though. Opinion, @agustincordes ?

**Comment by bd339** [comment]
Let me just add to the proposition above. We could still check if any audio objects will be reused in the target room before unloading it, of course. That should make it less wasteful.

**Comment by agustincordes** [comment]
Yes, keeping everything in memory per room sounds good, and in fact would give more importance to the idea of rooms as organisational objects rather than a mere grouping of nodes. Definitely like this approach!

**Comment by bd339** [comment]
Dealt with in #150.
